### ISSUE TITLE
All emails need to contain our company name, address, and link to privacy policy

### ISSUE THREAD

**Issue by ckarlof** [mozilla/fxa-auth-mailer#133]
Mozilla
331 E. Evelyn Avenue Mountain View, CA 94041
`<a href="https://www.mozilla.org/privacy" style="color: #0095dd; text-decoration: none; font-family: sans-serif;">Mozilla Privacy Policy</a>`

**Comment by vladikoff** [comment]
@ckarlof do we need this ASAP?

**Comment by ckarlof** [comment]
no, I'd say soon, though.

**Comment by ckarlof** [comment]
no.

**Comment by ryanfeeley** [comment]
We’d like to propose a small change to the address so that the body of the email can better maintain prominence:

CURRENT:

<b>Mozilla</b>
331 E. Evelyn Avenue Mountain View, CA 94041
<a>Mozilla Privacy Policy</a>


PROPOSED:

Mozilla. 331 E Evelyn Ave, Mountain View, CA 94041. <a href=#">Privacy Policy</a>
