### ISSUE TITLE
Add a query parameter to the "alternatively" link to log if anybody actually uses it.

### ISSUE THREAD

**Issue by shane-tomlinson** [mozilla/fxa-auth-mailer#188]
Another of @ryanfeeley's great ideas that is being typed up by me. The alternatively link is gigantic and ugly. If nobody (or very few people) are using it, we should get rid of it. How do we know if people are using it? We add a new query parameter to the alternatively link only, making the link longer. If the query parameter is there, then we know the user copied that link.

**Comment by ryanfeeley** [comment]
@davismtl @vbudhram @shane-tomlinson 

According to [this DataDog dashboard](https://app.datadoghq.com/dash/172590/fxa-content---emails?live=false&page=0&is_auto=false&from_ts=1471579200000&to_ts=1472011199999&tile_size=m&fullscreen=false)…

1.8% of registering users click the long link, while 4.8% of users signing in click the long link.

This tells me that it's safe to remove the long link from the verifcation because the link is so large that people are clicking it accidentally.

But that 4.8% for confirm sign-in should be removed immediately because users are probably thinking that it has a different purpose (like denying the sign-in).

How to proceed? Issues to remove both?

**Comment by shane-tomlinson** [comment]
@ryanfeeley - Hmmm... It's hard to validate assumptions about why people are clicking the secondary link w/o some sort of feedback mechanism. 

What's strange is that from the mail user-agent perspective, the two links are identical. Both the "button" and "link" use anchor elements, e.g., `<a href=...`. A mail client should handle these two identically if the user "clicks", perhaps some people actually copy/paste the secondary link instead of the primary link.

I wonder how we could AB test to ensure we don't cause a 1.8% drop in signup success and 4.8% drop in signin success.

Can you open an issue and we'll discuss?

**Comment by davismtl** [comment]
@shane-tomlinson said exactly what I was coming here to say. Can we A/B test to ensure we don't cause a drop in signup and signin success?

It should drop a bit due to the accidental clicks but there should be a migration to the button.

Other question, are we measure just absolute click numbers? Or are we measure users? If we are measuring users, we might realize that users are clicking both.
