### ISSUE TITLE
Decide title case styling, if any, for email subjects

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-auth-mailer#214]
Our copywriter is not on GitHub as far as I can tell, but I'll see her next week and determine the title case style, if any, we should use for our subject lines.

Right now it's a bit of a mish-mosh:
![screenshot 2016-09-23 09 49 51](https://cloud.githubusercontent.com/assets/68213/18788025/40d93a7e-8173-11e6-91b2-515db02e5062.png)

@shane-tomlinson @seanmonstar

**Comment by shane-tomlinson** [comment]
@ryanfeeley - I put your head on this because you said you were going to meet with the copywriter.

**Comment by mheubusch** [comment]
Hi - It seems like these are all sentence case except for the ones that say "Firefox Account Verified". If you just change the V to a v - Firefox Account verified - problem solved. (Note: Firefox Account is always capitalized because it is a proper noun.  If you are using "account" alone in a sentence, lower case.
