### ISSUE TITLE
Forgot your password title size mismatch

### ISSUE THREAD

**Issue by ryanfeeley** [mozilla/fxa-auth-mailer#217]
I noticed that the title of the "Forgot your password?" email does not match the size of our other emails. Correctable?

**Comment by vladikoff** [comment]
@ryanfeeley screenshot please :(

**Comment by ryanfeeley** [comment]
![screenshot 2016-09-29 11 47 14](https://cloud.githubusercontent.com/assets/68213/18961291/7c7c31be-863a-11e6-9d09-a102ae600124.png)

**Comment by vladikoff** [comment]
Thanks @ryanfeeley  !

**Comment by shane-tomlinson** [comment]
@ryanfeeley - both the "forgot your password" and "your password has been reset" use `h3` elements instead of `h1` like the others. Here's what they look like converted to `h1`:

<img width="359" alt="screen shot 2016-09-29 at 21 54 49" src="https://cloud.githubusercontent.com/assets/848085/18972051/7c0d1ab8-868f-11e6-81e4-b5f73f819269.png">
<img width="357" alt="screen shot 2016-09-29 at 21 54 53" src="https://cloud.githubusercontent.com/assets/848085/18972055/7ecee18c-868f-11e6-8626-5f8570089a9a.png">

**Comment by ryanfeeley** [comment]
Fantastic-o.
