### ISSUE TITLE
Mirror SalesForce Email Blacklist

### ISSUE THREAD

**Issue by davismtl** [mozilla/fxa-auth-mailer#256]
Marketing and FxA have a lot of overlap with email addresses to which we send to. We should  mirror each other's blacklists to help each other's sender scores.

If marketing sends a newsletter to an email that hard bounces, we probably shouldn't send a sign-in confirmation email to that address moving forward.

**Comment by shane-tomlinson** [comment]
@davismtl - this seems like a whole feature that should have a nice feature doc.

**Comment by seanmonstar** [comment]
FxA and Marketing use different senders, right?

Most reputation scores would not penalize for sending to a hard bounce the first time, since you possibly have a legitimate reason to try once: a user entered the email.

There is an exception, which is that some of these systems will create honeypot email addresses, and either leave them on obscure pages for scrapers to pick up, or submit them to known spam lists. The idea is, if you email that address, the only way you should have received it is scraping, or buy from a list, which would prove the unsolicited part of spam.

**Comment by shane-tomlinson** [comment]
I moved this to fxa-features, closing here.
