### ISSUE TITLE
[train-32] dropped email subjects 'Verify your account' and 'Reset your password'

### ISSUE THREAD

**Issue by jrgm** [mozilla/fxa-auth-mailer#31]
Github doesn't handle the big string change diffs, so look at, for example, `git show 3d39360 locale/fr/LC_MESSAGES/server.po` in fxa-content-server-l10n

That picked up some strings, noticeably "Almost there" that were missing, but appears to have dropped the email subjects.

**Comment by shane-tomlinson** [comment]
I believe the problem is the l10n-extract grunt task is set up to look only at the templates, and not at the .js files. All email subjects are in the .js files.

2 approaches I can think of:
* Add the email subjects to the templates. Subjects would be duplicated in the templates and JS, this is not very DRY.
* Update the l10n-extract script to look in the .js for translator.gettext
