### ISSUE TITLE
Improve our account verification email

### ISSUE THREAD

**Issue by pdehaan** [mozilla/fxa-auth-mailer#35]
(via @ryanfeeley in https://github.com/mozilla/fxa-content-server/issues/2315)

---

I think we can do better account verification email than this:

![fxa-email](https://cloud.githubusercontent.com/assets/68213/7119305/ae7b4e60-e1d2-11e4-8e15-14f0169bb05a.png)

Our conversion numbers are lower than I think they should be.

We should also consider sending this email when accounts go unverified (so copy should reflect this).

How to proceed?

**Comment by ryanfeeley** [comment]
Inspiration: http://ux.stackexchange.com/questions/43623/what-should-a-e-mail-address-confirmation-e-mail-say

**Comment by designakt** [comment]
Looks very serious and strait forward. So it definitely looks legitimate.
I still miss a logo in there. Something that quickly and visually tells the user who sent this. At best it looks very similar to where the user started signing up for the account. So the Firefox logo and maybe the cloud logo. Plus rounded corners as in the signup, if possible.
"Almost there" misses a punctuation mark, or if both lines should work as a sentence, then they are to far apart, and too different in size.
Can the button say "Verify Account", so that the user quickly know what is verified, without reading the sentence above?

**Comment by ryanfeeley** [comment]
Great gallery: http://reallygoodemails.com/category/confirmation/ @designakt @bryanbell

**Comment by ryanfeeley** [comment]
I wonder if I'm dreaming thinking that we can position the Firefox logo consistently in all email clients like this:

![fxa-email-activation](https://cloud.githubusercontent.com/assets/68213/7140251/4a0d73a6-e298-11e4-8674-f7008e25da79.png)

**Comment by phlsa** [comment]
That would be nice!
But even if the logo were outside the box or somewhere in a corner, it seems like a huge step up in terms of being identifiable.

**Comment by jrgm** [comment]
So, is there  a specific action/final design at this point?

**Comment by ryanfeeley** [comment]
I know @rfk has added this repo to waffle, so it can be considered at the next bug triage. I'm still discussing a few things like testing different button text, varying the resend message (Welcome!, Hello Again, Ahem Over Here, Last Chance, etc.), and HTML feasibility. Should be actionable by next week.

**Comment by ross999** [comment]
Hey guys - David here from htmlemailgallery.com - I just saw someone had tweeted at me and a few others asking about the logo positioning.

I'm assuming you're planning on using css for the email container? And using css for the box shadow and rounded corners? If so I don't think you'll be able to position the logo outside of the containing box. As we all know css support is not very good in many email clients. For a regular website we'd use css with a negative margin or absolute positioning to make the firefox logo stick out of the container. But for an email it would only work in few email clients because of the poor css support. 

It looks nice and could be achieved easily with images/tables obviously. For mobile devices you get pretty good css support with it so you could use a media query or two to show somewhat or a different styled email that would contort to the screen's size. With the image solution it may be difficult to have it adapt to mobile devices but it may be possible.

If you need coding help there are some advertisers on my site that are good and could be helpful.

Working on redoing my site right now. Been 7 years and it's been neglected so working on a new, responsive version - hopefully have time to finish it up within next few weeks.

Good luck with the email. 

-David

**Comment by ryanfeeley** [comment]
Thanks @ross999! I'm following the path of least resistance and suggesting we remove the frame and background entirely, avoiding any positioning issues. Here is the proposed design:
![activate](https://cloud.githubusercontent.com/assets/68213/7209053/ed6e2730-e512-11e4-87ee-b183d959c64c.png)
From: accounts@firefox.com (unchanged)
Subject line: Firefox Account Activation

**Comment by ross999** [comment]
I like it. Looks good with or without the border and yes, much less hassle without it sticking out. 

The button should be simple enough to code but thought I'd mention that Campaign Monitor has a nice email button generator that creates code for modern email clients and also adds support for versions of outlook. Just be sure to add url in regular code and ms specific code. See here: http://buttons.cm

-D

**Comment by johngruen** [comment]
@ryanfeeley not sure about 'alternatively as copy there'
also font size should match the boilerplate below as should the text color

**Comment by pdehaan** [comment]
I think I preferred the older copy of "... your Firefox Account" over the newer, less specific "... your account".

Also, here's a snippet from a recent email I got when signing up for npm:

> _To confirm that this is the email address associated with that account, click the following link or paste it into your browser:_
>
> https&#58;//www.npmjs.com/confirm-email/{{sha}}
>
> _If you received this in error, you can safely ignore it._
>
> _The request will expire in one week._

I like the part about "the request will expire in one week". It may give the user some sense of urgency to complete the verification, or help explain why the link won't work in 2 weeks when they get around to reading their email.

**Comment by ryanfeeley** [comment]
@johngruen I've never been happier about a word choice as I am with “alternatively”. A quick check of translations shows that it works well because it's a single word.

@pdehaan That line reads more fluidly as simply “account” as the subject line, sender and logo fill in the missing Firefox.

You are on to something about emails expiring, although I think the next piece will be sending reminder emails when accounts remain unverified for X days. Stay tuned for a future issue to address that.

**Comment by pdehaan** [comment]
@ryanfeeley My only concern is that if Google parses the email body and sees a generic "Please activate your account" and trigger some spam logic. I think the copy works fine for users, I guess I was only thinking of the email provider's potential spam filter logic.

**Comment by ryanfeeley** [comment]
@pdehaan Agreed, SPAM is a big deal and got us into trouble with "Congratulations". Not sure the effort, but ideally we can deploy measure button variants with combinations of:
* Activate / Confirm / Verify / Complete
* Your / My
* Account / Activation
* Now / Instantly / and Continue

**Comment by johngruen** [comment]
@ryanfeeley: ask your dad if he would understand what alternatively means in this context, i'll be fine with it if he answers correctly. 

I 100% agree with peter about adding Firefox Account back in there

**Comment by ryanfeeley** [comment]
@dad Thoughts?

**Comment by ryanfeeley** [comment]
@johngruen Response from my 75-year-old dad:
>
>I would take it to mean that I could click on "Activate Now"
>
> or click on the URL below "Alternatively"
>
> Failing that I could cut and paste the URL

Boom!

**Comment by johngruen** [comment]
Ship it

**Comment by johngruen** [comment]
@ryanfeeley here's the image we're going to use provisionally, Engagement is going to host if for us.
![fxa-email 2x](https://cloud.githubusercontent.com/assets/3323249/7237141/97da9734-e767-11e4-89b7-ad4a9f6bf3b3.gif)

**Comment by johngruen** [comment]
@ryanfeeley it will be scaled to half size in html, shipping a png is 2x as large size-wise

**Comment by bniolet** [comment]
Here's the image; 

http://image.e.mozilla.org/lib/fe9915707361037e75/m/2/firefox.gif

**Comment by vladikoff** [comment]
From https://github.com/mozilla/fxa-content-server/issues/1032, +1 on adding an extra verification link that is an alternative to the existing "Verify" button.

**Comment by ryanfeeley** [comment]
I am using an add-on that created a site-specific browser for my Gmail. No, right click and no popups, so I could use it too.
![fxa-alternatively](https://cloud.githubusercontent.com/assets/68213/7938900/04b09f1e-0916-11e5-9109-e20a07059c6d.png)

**Comment by vladikoff** [comment]
Should be fixed via https://github.com/mozilla/fxa-auth-mailer/commit/b8f5480703945ec26f72952adc9cc60ff9d71d82#diff-20ee765c36edf392537bf74d8d8d3d84R54
